In [ ]:
import numpy as np

In [ ]:
# 1. สร้างจาก List ธรรมดา
my_list = [1, 2, 3]
arr = np.array(my_list)
print(arr)  # ผลลัพธ์: [1 2 3]

[1 2 3]


In [ ]:
# 2. สร้างแบบระบุช่วง (เหมือน range)
arr_range = np.arange(0, 10, 2)
print(arr_range) # ผลลัพธ์: [0 2 4 6 8]

[0 2 4 6 8]


In [ ]:
# 3. สร้าง Array ที่มีแต่เลข 0 หรือ 1 (ใช้บ่อยตอนเตรียมข้อมูลภาพ หรือ initialize weights)
zeros = np.zeros((3, 3)) # สร้าง Matrix 3x3 ที่มีแต่เลข 0
ones = np.ones((2, 5))   # สร้าง Matrix 2x5 ที่มีแต่เลข 1

In [ ]:
data = np.array([10, 20, 30])

# ถ้าเป็น Python list ต้องวนลูป แต่ NumPy ทำแบบนี้ได้เลย:
print(data + 5)    # [15 25 35] (บวก 5 เข้าไปทุกตัว)
print(data * 2)    # [20 40 60] (คูณ 2 ทุกตัว)
print(data / 10)   # [1. 2. 3.]

[15 25 35]
[20 40 60]
[1. 2. 3.]


In [ ]:
# สร้าง Matrix 2x3 (2 แถว 3 คอลัมน์)
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

# การดึงค่า: [แถว, คอลัมน์]
print(matrix[0, 1])  # แถวที่ 0, คอลัมน์ที่ 1 -> ได้เลข 2
print(matrix[1, :])  # แถวที่ 1, เอาทุกคอลัมน์ -> ได้ [4 5 6]
print(matrix[:, 2])  # ทุกแถว, เอาเฉพาะคอลัมน์ที่ 2 -> ได้ [3 6]

2
[4 5 6]
[3 6]


In [11]:
arr = np.arange(12) # มีเลข 0-11 (12 ตัว)
print(arr.shape)    # (12,)

# เปลี่ยนเป็น Matrix 3 แถว 4 คอลัมน์
new_arr = arr.reshape(3, 4)
print(new_arr)
# [[ 0  1  2  3]
#  [ 4  5  6  7]
#  [ 8  9 10 11]]

(12,)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
